### ISSUE TITLE
Beautify output

### ISSUE THREAD

**Issue by kiliankoe** [kiliankoe/apodidae#21]
I'd love something like the fancy js spinner seen here for example:

![](https://github.com/sindresorhus/create-dmg/raw/master/screenshot-cli.gif)

And rethink colors, text styles and actual content everywhere. @hoodie suggested yaourt as inspiration:

![](https://archlinux.fr/wp-content/uploads/2007/06/yaourt_1.png)

**Comment by hoodie** [comment]
Cargo-fancy

**Comment by kiliankoe** [comment]
Ooooh, nice: https://asciinema.org/a/dbid3w8jqdpc7sauqdzkn784t

**Comment by kiliankoe** [comment]
First step: Write missing spinner library ✔︎ [kiliankoe/CLISpinner](https://github.com/kiliankoe/CLISpinner)
