### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by kiliankoe** [kiliankoe/apodidae#30]
After adding `Git.swift` with #26 Travis has started failing on running `swift test`

```
Undefined symbols for architecture x86_64:
  "__T08ShellOut05shellB0S2S2to_SaySSG9argumentsSS2attKF", referenced from:
      __T012ApodidaeCore3GitO17uncommitedChangesSb5Files6FolderC2in_tKFZ in Git.swift.o
ld: symbol(s) not found for architecture x86_64
```

Interestingly enough this only fails on `swift test`, `swift build` runs fine on Travis. What's happening here?

**Comment by kiliankoe** [comment]
Seeing the same thing locally now. Works from Xcode, `swift test` not so much.

**Comment by kiliankoe** [comment]
Fixed thanks to @BenchR267 😊

**Comment by BenchR267** [comment]
That's what I meant, the log says (a bit obfuscated) what it's problem is 😅
