### ISSUE TITLE
Rename add to install?

### ISSUE THREAD

**Issue by kiliankoe** [kiliankoe/apodidae#32]
Would really love some input from someone else on this 🙈 

Apodidae doesn't really install anything, it just tries to add to your package manifest and resolves it afterwards. 

`install` however does *feel* more natural coming from other tools.

**Comment by BenchR267** [comment]
yarn uses `add` as well (and they are installing it). I think add is better, also because it's shorter and describes the action better.

**Comment by kiliankoe** [comment]
Ah, good to know 👌 I had npm's install action in the back of my head.
