### ISSUE TITLE
Rename tool to `swift-github-catalog`

### ISSUE THREAD

**Issue by helje5** [kiliankoe/apodidae#43]
Apodidae is a thoughtful name, but certainly can't remember it :-) Just rename the whole thing to `swift-github-catalog` or sth.

**Comment by kiliankoe** [comment]
A rename to `swift-catalog` is probably a good idea. Apodidae is basically just a leftover, you gave the inspiration for the CLI's name, before that it was `apo`. 

I would still really love to support other "backends" besides GitHub, at least at some point in the future.

**Comment by helje5** [comment]
You could do something similar to Brew and support "taps".

**Comment by kiliankoe** [comment]
Renamed it to swift-library in lieu of the recent changes.
