### ISSUE TITLE
Cannot import Apodidae as package

### ISSUE THREAD

**Issue by helje5** [kiliankoe/apodidae#44]
Results in
```swift
error: the package https://github.com/kiliankoe/apodidae.git @ 0.5.0 contains revisioned dependencies:
    https://github.com/mxcl/PromiseKit @ swift4-beta1
```

**Comment by kiliankoe** [comment]
yeah... 😕 PromiseKit has since left its beta for Swift 4, but that resulted in breaking changes that need to be addressed 😢

**Comment by kiliankoe** [comment]
Possible now, even though it's probably no longer of relevance.
